import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { Providers } from './provider';

const noto = Noto_Sans({ subsets: ['latin'], weight: ['400', '500'] });

export const metadata: Metadata = {
  title: '¿Que me pongo?, by Eze Gatica',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`h-full bg-gray-900 ${noto.className}`}>
      <body className="h-full">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
