-- AlterTable
ALTER TABLE "RawReport" ALTER COLUMN "temp" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "temp_min" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "temp_max" SET DATA TYPE DOUBLE PRECISION;
